original_repo: https://github.com/hackcu/hackcu

volunteer_mentor_form: "https://forms.gle/CczF94ZWjidGAVou9"
live_page: "https://live.hackcu.org/"
register: "https://forms.gle/QQ2Uh12UD4AkZkrZ8"


description: "Join us for HackCU on February 22, 2020 at the University of Colorado Boulder."
title: HackCU 2020

sass:
    sass_dir: assets/_sass
    style: compressed